FROM envoyproxy/envoy:v1.17.0

COPY ./envoy.yaml /tmpl/envoy.yaml.tmpl
COPY docker-entrypoint.sh /

RUN chmod 500 /docker-entrypoint.sh

RUN apt-get update && \
    apt-get install gettext -y

ARG STATISTICO_FOOTBALL_DATA_HOST
ARG STATISTICO_FOOTBALL_DATA_PORT
ARG STATISTICO_ODDS_COMPILER_HOST
ARG STATISTICO_ODDS_COMPILER_PORT
ARG STATISTICO_ODDS_WAREHOUSE_HOST
ARG STATISTICO_ODDS_WAREHOUSE_PORT
ARG STATISTICO_RATINGS_HOST
ARG STATISTICO_RATINGS_PORT
ARG STATISTICO_TRADER_HOST
ARG STATISTICO_TRADER_PORT

ENV STATISTICO_FOOTBALL_DATA_HOST=${STATISTICO_FOOTBALL_DATA_HOST}
ENV STATISTICO_FOOTBALL_DATA_PORT=${STATISTICO_FOOTBALL_DATA_PORT}
ENV STATISTICO_ODDS_COMPILER_HOST=${STATISTICO_ODDS_COMPILER_HOST}
ENV STATISTICO_ODDS_COMPILER_PORT=${STATISTICO_ODDS_COMPILER_PORT}
ENV STATISTICO_ODDS_WAREHOUSE_HOST=${STATISTICO_ODDS_WAREHOUSE_HOST}
ENV STATISTICO_ODDS_WAREHOUSE_PORT=${STATISTICO_ODDS_WAREHOUSE_PORT}
ENV STATISTICO_RATINGS_HOST=${STATISTICO_RATINGS_HOST}
ENV STATISTICO_RATINGS_PORT=${STATISTICO_RATINGS_PORT}
ENV STATISTICO_TRADER_HOST=${STATISTICO_TRADER_HOST}
ENV STATISTICO_TRADER_PORT=${STATISTICO_TRADER_PORT}

EXPOSE 8080
EXPOSE 9900

ENTRYPOINT ["/docker-entrypoint.sh"]
