version: "3.3"
services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - statistico_internal
    mem_limit: 1024M
    mem_reservation: 256M
    environment:
      STATISTICO_FOOTBALL_DATA_HOST: statistico-football-data-grpc
      STATISTICO_FOOTBALL_DATA_PORT: 50051
      STATISTICO_ODDS_COMPILER_HOST: statistico-odds-compiler.statistico.internal
      STATISTICO_ODDS_COMPILER_PORT: 50051
      STATISTICO_RATINGS_HOST: statistico-ratings-grpc
      STATISTICO_RATINGS_PORT: 50051
      STATISTICO_TRADER_HOST: statistico-trader-grpc
      STATISTICO_TRADER_PORT: 50051

    ports:
      - "9900:9900"
      - "8080:8080"

networks:
  statistico_internal:
    external: true
