version: "3.7"
services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1024M
    mem_reservation: 256M
    environment:
      STATISTICO_FOOTBALL_DATA_HOST: statistico-football-data.statistico.internal
      STATISTICO_FOOTBALL_DATA_PORT: 50051
      STATISTICO_RATINGS_HOST: statistico-ratings.statistico.internal
      STATISTICO_RATINGS_PORT: 50051
