version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecs: circleci/aws-ecs@3.1.0

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - release-images:
          context: aws
          filters:
            branches:
              only: master
      - deploy-to-production:
          context: aws
          requires:
            - release-images
          filters:
            branches:
              only: master

jobs:
  release-images:
    executor: aws-cli/default
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup
      - run:
          name: Build and push images to ECR
          command: |
            aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | bash
            docker build \
              --build-arg STATISTICO_FOOTBALL_DATA_HOST=statistico-football-data.statistico.internal \
              --build-arg STATISTICO_FOOTBALL_DATA_PORT=50051 \
              --build-arg STATISTICO_ODDS_COMPILER_HOST=statistico-odds-compiler.statistico.internal \
              --build-arg STATISTICO_ODDS_COMPILER_PORT=50051 \
              --build-arg STATISTICO_RATINGS_HOST=statistico-ratings.statistico.internal \
              --build-arg STATISTICO_RATINGS_PORT=50051 \
              --build-arg STATISTICO_TRADER_HOST=statistico-trader.statistico.internal \
              --build-arg STATISTICO_TRADER_PORT=50051 \
              -t $AWS_ECR_ACCOUNT_URL/statistico-envoy-proxy:latest -f ./Dockerfile .
            docker push $AWS_ECR_ACCOUNT_URL/statistico-envoy-proxy:latest

  deploy-to-production:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/setup
      - aws-ecs/update-service:
          family: 'statistico-envoy-proxy'
          cluster: 'statistico-grpc-services'
          container-image-name-updates: >
            container=statistico-envoy-proxy,tag=latest
